Ensure `err.args` is defined when checking errors in `ConnectionInstance`